# Generated by Django 5.0.6 on 2024-09-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Routeop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length_km", models.FloatField()),
                ("polyline", models.TextField()),
                (
                    "end_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_end",
                        to="Routeop.busstop",
                    ),
                ),
                (
                    "start_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_start",
                        to="Routeop.busstop",
                    ),
                ),
            ],
        ),
    ]
