# Generated by Django 5.0.6 on 2024-09-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Routeop", "0002_alter_busstop_name_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="route",
            name="end_stop",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_stop",
        ),
        migrations.CreateModel(
            name="TravelRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length_km", models.FloatField()),
                ("polyline", models.TextField()),
                (
                    "end_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_end",
                        to="Routeop.stop",
                    ),
                ),
                (
                    "start_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_start",
                        to="Routeop.stop",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BusStop",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
    ]
