# Generated by Django 5.0.6 on 2024-09-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Routeop", "0003_stop_remove_route_end_stop_remove_route_start_stop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name="travelroute",
            old_name="length_km",
            new_name="distance",
        ),
        migrations.RemoveField(
            model_name="travelroute",
            name="polyline",
        ),
        migrations.AddField(
            model_name="travelroute",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="travelroute",
            name="end_stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_routes",
                to="Routeop.stop",
            ),
        ),
        migrations.AlterField(
            model_name="travelroute",
            name="start_stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_routes",
                to="Routeop.stop",
            ),
        ),
    ]
